version: "3.9"
services:
  app:
    container_name: app
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - "./data:/data/db"
    ports:
      - "27017:27017"
